"use client";

import { Check, LoaderCircle, LockKeyhole, Palette, Plus, Save, ShieldCheck, Type, X } from "lucide-react";
import { useState } from "react";
import type { BrandSettings } from "../lib/types";

interface Props{brand:BrandSettings;onSaved:(brand:BrandSettings)=>void;notify:(message:string)=>void}

export function BrandKitView({brand,onSaved,notify}:Props) {
  const [draft,setDraft]=useState(brand),[sponsor,setSponsor]=useState(""),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false);
  const update=<K extends keyof BrandSettings>(key:K,value:BrandSettings[K])=>{setDraft((current)=>({...current,[key]:value}));setDirty(true)};
  const save=async()=>{setSaving(true);try{const response=await fetch("/api/workspace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"brand_update",...draft})});const data=await response.json() as {brand?:BrandSettings;error?:string};if(!response.ok||!data.brand)throw new Error(data.error||"Sauvegarde impossible");setDraft(data.brand);onSaved(data.brand);setDirty(false);notify("Brand Kit NOCTYS mis à jour.")}catch(error){notify(error instanceof Error?error.message:"Le Brand Kit n’a pas pu être sauvegardé.")}finally{setSaving(false)}};
  const addSponsor=()=>{const value=sponsor.trim();if(!value||draft.sponsors.includes(value))return;update("sponsors",[...draft.sponsors,value]);setSponsor("")};
  const colors=[{key:"primaryColor",name:"Noctys Purple"},{key:"backgroundColor",name:"Night Core"},{key:"textColor",name:"Moon White"},{key:"mutedColor",name:"Steel Mist"}] as const;
  return <div className="view-stack fade-in brand-kit-view">
    <section className="section-heading brand-heading"><div><span className="eyebrow">IDENTITÉ — 07</span><h1>BRAND<br/><em>KIT.</em></h1></div><div className="brand-save"><div className="brand-health"><ShieldCheck size={18}/><div><strong>CHARTE CONFORME</strong><span>{draft.sponsors.length} sponsor{draft.sponsors.length>1?"s":""} · logo protégé</span></div></div><button className="primary" onClick={()=>void save()} disabled={!dirty||saving}>{saving?<LoaderCircle className="spin" size={14}/>:<Save size={14}/>} {dirty?"Sauvegarder":"À jour"}</button></div></section>
    <section className="brand-grid">
      <article className="brand-panel logo-vault"><div className="brand-panel-title"><div><LockKeyhole size={16}/><span>LOGO MAÎTRE</span></div><small>ÉLÉMENT VERROUILLÉ</small></div><div className="brand-logo-stage"><img src={draft.logoUrl} alt="Logo officiel NOCTYS"/><span>ZONE DE PROTECTION ACTIVE</span></div><p>Le logo officiel est injecté dans les packs et protégé contre les déformations.</p></article>
      <article className="brand-panel"><div className="brand-panel-title"><div><Palette size={16}/><span>PALETTE OFFICIELLE</span></div><small>NOCTYS v2.1</small></div><div className="brand-swatches">{colors.map((color)=><label key={color.key}><input type="color" value={draft[color.key]} onChange={(event)=>update(color.key,event.target.value)}/><span><strong>{color.name}</strong><input value={draft[color.key]} onChange={(event)=>update(color.key,event.target.value)}/></span><Check size={13}/></label>)}</div></article>
      <article className="brand-panel brand-type"><div className="brand-panel-title"><div><Type size={16}/><span>SYSTÈME TYPOGRAPHIQUE</span></div></div><div className="type-sample michroma"><span>TITRES</span><strong>ENTER THE NIGHT</strong><small>{draft.headlineFont} · 400</small></div><div className="type-sample rajdhani"><span>INTERFACE</span><strong>MATCH NIGHT — BO3</strong><small>Rajdhani · 700</small></div><div className="type-sample inter"><span>TEXTE</span><strong>La nuit appartient à NOCTYS.</strong><small>{draft.bodyFont} · 500</small></div><label className="brand-text-field">Signature officielle<input value={draft.signature} onChange={(event)=>update("signature",event.target.value)}/></label><label className="brand-text-field">Ton rédactionnel<textarea value={draft.tone} onChange={(event)=>update("tone",event.target.value)}/></label></article>
      <article className="brand-panel brand-rules"><div className="brand-panel-title"><div><ShieldCheck size={16}/><span>SPONSORS & RÈGLES</span></div></div><div className="sponsor-add"><input value={sponsor} onChange={(event)=>setSponsor(event.target.value)} placeholder="Ajouter un sponsor" onKeyDown={(event)=>{if(event.key==="Enter"){event.preventDefault();addSponsor()}}}/><button onClick={addSponsor}><Plus size={14}/></button></div><div className="sponsor-list">{draft.sponsors.map((item)=><span key={item}>{item}<button onClick={()=>update("sponsors",draft.sponsors.filter((value)=>value!==item))} aria-label={`Retirer ${item}`}><X size={11}/></button></span>)}{!draft.sponsors.length&&<small>Aucun sponsor configuré.</small>}</div>{["Contraste minimum vérifié","Logo présent avant validation","Palette contrôlée au préflight"].map((rule)=><div className="brand-rule" key={rule}><Check size={14}/><span>{rule}</span></div>)}</article>
    </section>
  </div>;
}
